title: Troop 372 Website
author: Harry G. Evans
email: hgevans@bellsouth.net
description: This is a test description for the gitbut pages learning module while setting up the Troop 372 website.

# social links
twitter_username: your-twitter-handle
github_username:  evansclan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
